import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookieToInitialState } from "wagmi";
import { getConfig } from "@/utils/configWagmi";
import { headers } from "next/headers";
import { Providers } from "@/components/provider";
import Link from "next/link";
import { IoSearchOutline } from "react-icons/io5";

import "@rainbow-me/rainbowkit/styles.css";

import { ButtonStyle } from "@/components/connectButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    getConfig(),
    (await headers()).get("cookie")
  );

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers initialState={initialState}>
          <TopBar /> {children}
        </Providers>
      </body>
    </html>
  );
}

export function TopBar() {
  return (
    <div className="h-[90px] w-100% bg-background-alt font-SpaceGrotesk">
      <div className="h-full w-full flex items-center">
        <div className="size-12 ml-4 -mt-1 rounded-full bg-white" />
        <h1 className="ml-2 text-[22px] text-white">Vault Marketplace</h1>
        {/* <div>
          <button onClick={() => setIsMenuOpen(!isMenuOpen)}>
            {isMenuOpen ? (
              <img src="/icons/delete.png" />
            ) : (
              <img src="/icons/hamburguer.png" />
            )}
          </button>
        </div> */}
        <Link href={`/explore-vaults`}>
          <h2 className="ml-10 flex hover:underline text-text-foreground">
            <IoSearchOutline className="size-[18px] mt-0.5 mr-1" /> Explore
            vaults
          </h2>
        </Link>
        <Link href="/create-vault-page">
          <h3 className="ml-8 flex text-white items-center hover:underline">
            <p
              className="size-3.5 bg-text-foreground flex rounded-full items-center justify-center text-sm 
            font-semibold mr-1.5 -mt-0.5 text-black"
            >
              +
            </p>
            Create a vault
          </h3>
        </Link>
        <div className=" ml-auto mr-4">
          <ButtonStyle />
        </div>
      </div>
    </div>
  );
}

export function MenuSelect() {
  return (
    <div>
      <div></div>
    </div>
  );
}
