import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookieToInitialState } from "wagmi";
import { getConfig } from "@/utils/configWagmi";
import { headers } from "next/headers";
import { Providers } from "@/components/Providers";
import "@rainbow-me/rainbowkit/styles.css";
import { TopBar } from "@/components/topBar";
import { Button } from "@/components/interface/button";
import { FaDiscord } from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    getConfig(),
    (await headers()).get("cookie")
  );

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers initialState={initialState}>
          <TopBar /> {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}

function Footer() {
  return (
    <div className="min-w-full min-h-full bg-background pt-8 px-2">
      <div className="line h-0.5 bg-gray-500 my-8" />
      <div className="flex items-center gap-2">
        <p className="pl-8 text-sm text-gray-400">
          To service provider or just report a bug:
        </p>
        <a>
          <span className="text-white hover:underline text-xl font-semibold">
            Contact Us
          </span>
        </a>
      </div>
      <div className="line h-0.5 bg-gray-500 my-8" />
      <div className="flex items-center gap-2 text-gray-400 pb-8">
        <div className="flex items-center  gap-2 text-sm pl-8">
          <p className="hover:underline">Documentation</p>
          <p className="hover:underline">Terms & Conditions</p>
          <p className="hover:underline">Privacy Policy</p>
          <p className="hover:underline ">Account Verification</p>
        </div>
        <p className="text-sm ml-auto ">Follow Us:</p>
        <a href="https://discord.com/" target="_blank">
          <Button
            className="flex gap-1 hover:bg-none"
            intent="neutral"
            size="medium"
          >
            <FaDiscord />
            Discord
          </Button>
        </a>
        <a href="https://x.com" target="_blank">
          <Button
            className="flex gap-1 hover:bg-none"
            intent="neutral"
            size="medium"
          >
            <FaXTwitter />
            Twitter
          </Button>
        </a>
      </div>
    </div>
  );
}
